<?php
/**
 * MdfeSefazTrem
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NuvemFiscal\Model;

use \ArrayAccess;
use \NuvemFiscal\ObjectSerializer;

/**
 * MdfeSefazTrem Class Doc Comment
 *
 * @category Class
 * @description Informações da composição do trem.
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MdfeSefazTrem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MdfeSefazTrem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'x_pref' => 'string',
        'dh_trem' => '\DateTime',
        'x_ori' => 'string',
        'x_dest' => 'string',
        'q_vag' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'x_pref' => null,
        'dh_trem' => 'date-time',
        'x_ori' => null,
        'x_dest' => null,
        'q_vag' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'x_pref' => true,
        'dh_trem' => true,
        'x_ori' => true,
        'x_dest' => true,
        'q_vag' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'x_pref' => 'xPref',
        'dh_trem' => 'dhTrem',
        'x_ori' => 'xOri',
        'x_dest' => 'xDest',
        'q_vag' => 'qVag'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'x_pref' => 'setXPref',
        'dh_trem' => 'setDhTrem',
        'x_ori' => 'setXOri',
        'x_dest' => 'setXDest',
        'q_vag' => 'setQVag'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'x_pref' => 'getXPref',
        'dh_trem' => 'getDhTrem',
        'x_ori' => 'getXOri',
        'x_dest' => 'getXDest',
        'q_vag' => 'getQVag'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('x_pref', $data ?? [], null);
        $this->setIfExists('dh_trem', $data ?? [], null);
        $this->setIfExists('x_ori', $data ?? [], null);
        $this->setIfExists('x_dest', $data ?? [], null);
        $this->setIfExists('q_vag', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['x_pref'] === null) {
            $invalidProperties[] = "'x_pref' can't be null";
        }
        if ((mb_strlen($this->container['x_pref']) > 10)) {
            $invalidProperties[] = "invalid value for 'x_pref', the character length must be smaller than or equal to 10.";
        }

        if ((mb_strlen($this->container['x_pref']) < 1)) {
            $invalidProperties[] = "invalid value for 'x_pref', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['x_ori'] === null) {
            $invalidProperties[] = "'x_ori' can't be null";
        }
        if ((mb_strlen($this->container['x_ori']) > 3)) {
            $invalidProperties[] = "invalid value for 'x_ori', the character length must be smaller than or equal to 3.";
        }

        if ((mb_strlen($this->container['x_ori']) < 1)) {
            $invalidProperties[] = "invalid value for 'x_ori', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['x_dest'] === null) {
            $invalidProperties[] = "'x_dest' can't be null";
        }
        if ((mb_strlen($this->container['x_dest']) > 3)) {
            $invalidProperties[] = "invalid value for 'x_dest', the character length must be smaller than or equal to 3.";
        }

        if ((mb_strlen($this->container['x_dest']) < 1)) {
            $invalidProperties[] = "invalid value for 'x_dest', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['q_vag'] === null) {
            $invalidProperties[] = "'q_vag' can't be null";
        }
        if (($this->container['q_vag'] > 999)) {
            $invalidProperties[] = "invalid value for 'q_vag', must be smaller than or equal to 999.";
        }

        if (($this->container['q_vag'] < 1)) {
            $invalidProperties[] = "invalid value for 'q_vag', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets x_pref
     *
     * @return string
     */
    public function getXPref()
    {
        return $this->container['x_pref'];
    }

    /**
     * Sets x_pref
     *
     * @param string $x_pref Prefixo do Trem.
     *
     * @return self
     */
    public function setXPref($x_pref)
    {
        if (is_null($x_pref)) {
            array_push($this->openAPINullablesSetToNull, 'x_pref');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('x_pref', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($x_pref) && (mb_strlen($x_pref) > 10)) {
            throw new \InvalidArgumentException('invalid length for $x_pref when calling MdfeSefazTrem., must be smaller than or equal to 10.');
        }
        if (!is_null($x_pref) && (mb_strlen($x_pref) < 1)) {
            throw new \InvalidArgumentException('invalid length for $x_pref when calling MdfeSefazTrem., must be bigger than or equal to 1.');
        }

        $this->container['x_pref'] = $x_pref;

        return $this;
    }

    /**
     * Gets dh_trem
     *
     * @return \DateTime|null
     */
    public function getDhTrem()
    {
        return $this->container['dh_trem'];
    }

    /**
     * Sets dh_trem
     *
     * @param \DateTime|null $dh_trem Data e hora de liberação do trem na origem.
     *
     * @return self
     */
    public function setDhTrem($dh_trem)
    {
        if (is_null($dh_trem)) {
            array_push($this->openAPINullablesSetToNull, 'dh_trem');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dh_trem', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dh_trem'] = $dh_trem;

        return $this;
    }

    /**
     * Gets x_ori
     *
     * @return string
     */
    public function getXOri()
    {
        return $this->container['x_ori'];
    }

    /**
     * Sets x_ori
     *
     * @param string $x_ori Origem do Trem.  Sigla da estação de origem.
     *
     * @return self
     */
    public function setXOri($x_ori)
    {
        if (is_null($x_ori)) {
            array_push($this->openAPINullablesSetToNull, 'x_ori');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('x_ori', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($x_ori) && (mb_strlen($x_ori) > 3)) {
            throw new \InvalidArgumentException('invalid length for $x_ori when calling MdfeSefazTrem., must be smaller than or equal to 3.');
        }
        if (!is_null($x_ori) && (mb_strlen($x_ori) < 1)) {
            throw new \InvalidArgumentException('invalid length for $x_ori when calling MdfeSefazTrem., must be bigger than or equal to 1.');
        }

        $this->container['x_ori'] = $x_ori;

        return $this;
    }

    /**
     * Gets x_dest
     *
     * @return string
     */
    public function getXDest()
    {
        return $this->container['x_dest'];
    }

    /**
     * Sets x_dest
     *
     * @param string $x_dest Destino do Trem.  Sigla da estação de destino.
     *
     * @return self
     */
    public function setXDest($x_dest)
    {
        if (is_null($x_dest)) {
            array_push($this->openAPINullablesSetToNull, 'x_dest');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('x_dest', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($x_dest) && (mb_strlen($x_dest) > 3)) {
            throw new \InvalidArgumentException('invalid length for $x_dest when calling MdfeSefazTrem., must be smaller than or equal to 3.');
        }
        if (!is_null($x_dest) && (mb_strlen($x_dest) < 1)) {
            throw new \InvalidArgumentException('invalid length for $x_dest when calling MdfeSefazTrem., must be bigger than or equal to 1.');
        }

        $this->container['x_dest'] = $x_dest;

        return $this;
    }

    /**
     * Gets q_vag
     *
     * @return int
     */
    public function getQVag()
    {
        return $this->container['q_vag'];
    }

    /**
     * Sets q_vag
     *
     * @param int $q_vag Quantidade de vagões carregados.
     *
     * @return self
     */
    public function setQVag($q_vag)
    {
        if (is_null($q_vag)) {
            array_push($this->openAPINullablesSetToNull, 'q_vag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('q_vag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($q_vag) && ($q_vag > 999)) {
            throw new \InvalidArgumentException('invalid value for $q_vag when calling MdfeSefazTrem., must be smaller than or equal to 999.');
        }
        if (!is_null($q_vag) && ($q_vag < 1)) {
            throw new \InvalidArgumentException('invalid value for $q_vag when calling MdfeSefazTrem., must be bigger than or equal to 1.');
        }

        $this->container['q_vag'] = $q_vag;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


