<?php
/**
 * NfeSefazCard
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Nuvem Fiscal
 *
 * API para automação comercial e documentos fiscais.
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace NuvemFiscal\Model;

use \ArrayAccess;
use \NuvemFiscal\ObjectSerializer;

/**
 * NfeSefazCard Class Doc Comment
 *
 * @category Class
 * @description Grupo de Cartões, PIX, Boletos e outros Pagamentos Eletrônicos.
 * @package  NuvemFiscal
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class NfeSefazCard implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'NfeSefazCard';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tp_integra' => 'int',
        'cnpj' => 'string',
        't_band' => 'string',
        'c_aut' => 'string',
        'cnpj_receb' => 'string',
        'id_term_pag' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tp_integra' => null,
        'cnpj' => null,
        't_band' => null,
        'c_aut' => null,
        'cnpj_receb' => null,
        'id_term_pag' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tp_integra' => true,
        'cnpj' => true,
        't_band' => true,
        'c_aut' => true,
        'cnpj_receb' => true,
        'id_term_pag' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tp_integra' => 'tpIntegra',
        'cnpj' => 'CNPJ',
        't_band' => 'tBand',
        'c_aut' => 'cAut',
        'cnpj_receb' => 'CNPJReceb',
        'id_term_pag' => 'idTermPag'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tp_integra' => 'setTpIntegra',
        'cnpj' => 'setCnpj',
        't_band' => 'setTBand',
        'c_aut' => 'setCAut',
        'cnpj_receb' => 'setCnpjReceb',
        'id_term_pag' => 'setIdTermPag'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tp_integra' => 'getTpIntegra',
        'cnpj' => 'getCnpj',
        't_band' => 'getTBand',
        'c_aut' => 'getCAut',
        'cnpj_receb' => 'getCnpjReceb',
        'id_term_pag' => 'getIdTermPag'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tp_integra', $data ?? [], null);
        $this->setIfExists('cnpj', $data ?? [], null);
        $this->setIfExists('t_band', $data ?? [], null);
        $this->setIfExists('c_aut', $data ?? [], null);
        $this->setIfExists('cnpj_receb', $data ?? [], null);
        $this->setIfExists('id_term_pag', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tp_integra'] === null) {
            $invalidProperties[] = "'tp_integra' can't be null";
        }
        if (!is_null($this->container['cnpj']) && (mb_strlen($this->container['cnpj']) > 14)) {
            $invalidProperties[] = "invalid value for 'cnpj', the character length must be smaller than or equal to 14.";
        }

        if (!is_null($this->container['c_aut']) && (mb_strlen($this->container['c_aut']) > 128)) {
            $invalidProperties[] = "invalid value for 'c_aut', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['c_aut']) && (mb_strlen($this->container['c_aut']) < 1)) {
            $invalidProperties[] = "invalid value for 'c_aut', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['cnpj_receb']) && (mb_strlen($this->container['cnpj_receb']) > 14)) {
            $invalidProperties[] = "invalid value for 'cnpj_receb', the character length must be smaller than or equal to 14.";
        }

        if (!is_null($this->container['id_term_pag']) && (mb_strlen($this->container['id_term_pag']) > 40)) {
            $invalidProperties[] = "invalid value for 'id_term_pag', the character length must be smaller than or equal to 40.";
        }

        if (!is_null($this->container['id_term_pag']) && (mb_strlen($this->container['id_term_pag']) < 1)) {
            $invalidProperties[] = "invalid value for 'id_term_pag', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tp_integra
     *
     * @return int
     */
    public function getTpIntegra()
    {
        return $this->container['tp_integra'];
    }

    /**
     * Sets tp_integra
     *
     * @param int $tp_integra Tipo de Integração do processo de pagamento com o sistema de automação da empresa:  * 1 - Pagamento integrado com o sistema de automação da empresa (Ex.: equipamento TEF, Comércio Eletrônico, POS Integrado)  * 2 - Pagamento não integrado com o sistema de automação da empresa (Ex.: equipamento POS Simples)
     *
     * @return self
     */
    public function setTpIntegra($tp_integra)
    {
        if (is_null($tp_integra)) {
            array_push($this->openAPINullablesSetToNull, 'tp_integra');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tp_integra', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tp_integra'] = $tp_integra;

        return $this;
    }

    /**
     * Gets cnpj
     *
     * @return string|null
     */
    public function getCnpj()
    {
        return $this->container['cnpj'];
    }

    /**
     * Sets cnpj
     *
     * @param string|null $cnpj CNPJ da instituição de pagamento.
     *
     * @return self
     */
    public function setCnpj($cnpj)
    {
        if (is_null($cnpj)) {
            array_push($this->openAPINullablesSetToNull, 'cnpj');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cnpj', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($cnpj) && (mb_strlen($cnpj) > 14)) {
            throw new \InvalidArgumentException('invalid length for $cnpj when calling NfeSefazCard., must be smaller than or equal to 14.');
        }

        $this->container['cnpj'] = $cnpj;

        return $this;
    }

    /**
     * Gets t_band
     *
     * @return string|null
     */
    public function getTBand()
    {
        return $this->container['t_band'];
    }

    /**
     * Sets t_band
     *
     * @param string|null $t_band Bandeira da operadora de cartão.
     *
     * @return self
     */
    public function setTBand($t_band)
    {
        if (is_null($t_band)) {
            array_push($this->openAPINullablesSetToNull, 't_band');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('t_band', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['t_band'] = $t_band;

        return $this;
    }

    /**
     * Gets c_aut
     *
     * @return string|null
     */
    public function getCAut()
    {
        return $this->container['c_aut'];
    }

    /**
     * Sets c_aut
     *
     * @param string|null $c_aut Número de autorização da operação com cartões, PIX, boletos e outros pagamentos eletrônicos.
     *
     * @return self
     */
    public function setCAut($c_aut)
    {
        if (is_null($c_aut)) {
            array_push($this->openAPINullablesSetToNull, 'c_aut');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('c_aut', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($c_aut) && (mb_strlen($c_aut) > 128)) {
            throw new \InvalidArgumentException('invalid length for $c_aut when calling NfeSefazCard., must be smaller than or equal to 128.');
        }
        if (!is_null($c_aut) && (mb_strlen($c_aut) < 1)) {
            throw new \InvalidArgumentException('invalid length for $c_aut when calling NfeSefazCard., must be bigger than or equal to 1.');
        }

        $this->container['c_aut'] = $c_aut;

        return $this;
    }

    /**
     * Gets cnpj_receb
     *
     * @return string|null
     */
    public function getCnpjReceb()
    {
        return $this->container['cnpj_receb'];
    }

    /**
     * Sets cnpj_receb
     *
     * @param string|null $cnpj_receb CNPJ do beneficiário do pagamento.
     *
     * @return self
     */
    public function setCnpjReceb($cnpj_receb)
    {
        if (is_null($cnpj_receb)) {
            array_push($this->openAPINullablesSetToNull, 'cnpj_receb');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cnpj_receb', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($cnpj_receb) && (mb_strlen($cnpj_receb) > 14)) {
            throw new \InvalidArgumentException('invalid length for $cnpj_receb when calling NfeSefazCard., must be smaller than or equal to 14.');
        }

        $this->container['cnpj_receb'] = $cnpj_receb;

        return $this;
    }

    /**
     * Gets id_term_pag
     *
     * @return string|null
     */
    public function getIdTermPag()
    {
        return $this->container['id_term_pag'];
    }

    /**
     * Sets id_term_pag
     *
     * @param string|null $id_term_pag Identificador do terminal de pagamento.
     *
     * @return self
     */
    public function setIdTermPag($id_term_pag)
    {
        if (is_null($id_term_pag)) {
            array_push($this->openAPINullablesSetToNull, 'id_term_pag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_term_pag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($id_term_pag) && (mb_strlen($id_term_pag) > 40)) {
            throw new \InvalidArgumentException('invalid length for $id_term_pag when calling NfeSefazCard., must be smaller than or equal to 40.');
        }
        if (!is_null($id_term_pag) && (mb_strlen($id_term_pag) < 1)) {
            throw new \InvalidArgumentException('invalid length for $id_term_pag when calling NfeSefazCard., must be bigger than or equal to 1.');
        }

        $this->container['id_term_pag'] = $id_term_pag;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


